matrix:
  include:
    - language: node.js
      before_script:
        - cd detector-api
        - npm install
        - npm run build
      script:
        - npm run test
    
    - language: node.js
      before_script:
        - cd detector-app
        - npm install
        - npm run build
      script:
        - npm run test
