matrix:
  include:
    - language: node_js
      dist: trusty
      before_script:
        - cd detector-api
        - npm install
      script:
        - npm run build
        - npm run test
    
    - language: node_js
      dist: trusty
      cache:
        directories:
          - node_modules
      addons:
        chrome: stable
      before_script:
        - cd detector-app
        - npm install
      script:
        - npm run build
        - npm run test
        - xvfb-run npm run e2e
