matrix:
  include:
    - language: node_js
      before_script:
        - cd detector-api
        - npm install
        - npm run build
      
    - language: node_js
      sudo: required
      dist: trusty
      addons:
        chrome: stable
      cache:
        directories:
          - node_modules
      before_install:
        - export CHROME_BIN=/usr/bin/google-chrome
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
      before_script:
        - cd detector-app
        - npm install
        - npm run build
        