matrix:
  include:
    - language: node_js
      before_script:
        - cd detector-api
        - npm install
      script:
        - npm run build
        - npm run test
    
    - language: node_js
      cache:
        directories:
          - node_modules
      addons:
        firefox: latest
      before_install:
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
        - sleep 3
      before_script:
        - cd detector-app
